[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["bigredbutton"]

[tool.hatch.build.targets.wheel]
include = ["bigredbutton"]

[project]
name = "django-bigredbutton"
version = "0.3.2"
description = "Django app that offers a big red button to sign out of all other user sessions"
authors = [{ name = "blag", email = "blag@users.noreply.github.com" }]
requires-python = ">=3.11"
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 4.1",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP :: Session",
    "Topic :: Security",
]
dependencies = [
    "django>=4.0",
    # Also required by django-qsessions, but we use types provided from it, so we require it as well
    "user-agents>=2.2.0",
]

[project.optional-dependencies]
qsessions = ["django-qsessions>=1.1.4"]
user-sessions = ["django-user-sessions>=2.0.0"]

[dependency-groups]
qsessions = ["django-qsessions>=1.1.4"]
user-sessions = ["django-user-sessions>=2.0.0"]
test = [
    "coverage[toml]>=7.3.2,<8",
    "geoip2>=4.7.0",
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "pytest-django>=4.6.0",
]

[tool.uv]
default-groups = [
    "qsessions",
    "user-sessions",
    "test",
]

[tool.coverage.run]
branch = true
source = [
	"bigredbutton",
]
omit =[
    "*venv*",
	"*site-packages*",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tests.settings"
addopts = "--cov"
norecursedirs = ".git"
pythonpath = ["."]

[tool.ruff]
line-length = 100
