on:
  release:
    types:
      - published

name: PyPI Publish

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
      url: https://pypi.org/p/django-bigredbutton
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install latest version of Poetry
        run: |
          pipx install poetry
          dirname $(which poetry) >> $GITHUB_PATH
          echo "GITHUB_PATH:"
          cat $GITHUB_PATH
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: poetry
          cache-dependency-path: pyproject.toml
      - name: Get Poetry version
        run: |
          echo "GITHUB_PATH:"
          cat $GITHUB_PATH
          poetry --version
      - name: Check pyproject.toml validity
        run: poetry check --no-interaction
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
      - name: Build package
        run: |
          poetry build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          verbose: true
